export const ACTION_TYPES__CHAT_SET_APP_LOADING_STATE = 'ACTION_TYPES__CHAT_SET_APP_LOADING_STATE';
export const ACTION_TYPES__CHAT_SET_CURRENT_ROUTE = 'ACTION_TYPES__CHAT_SET_CURRENT_ROUTE';
export const ACTION_TYPES__CHAT_SET_USERS = 'ACTION_TYPES__CHAT_SET_USERS';
export const ACTION_TYPES__CHAT_SET_CURRENT_USER = 'ACTION_TYPES__CHAT_SET_CURRENT_USER';
